export type Locale = 'en' | 'ru' | 'kk';
export const COPY = {
  en: {
    title: 'Light,<br><em>in layers.</em>', kicker:'L–01 · An optical study', intro:'A lens, taken apart.<br>A closer look at what makes an image.',
    explore:'Explore the lens', inside:'Inside', notes:'The study', scroll:'Scroll to discover', back:'Back to the lens', replay:'Experience it again',
    chapters:['Form','Separation','Layers','Aperture','Together'],
    captions:[
      ['A quiet beginning.','One complete object. Many precise decisions.'],
      ['Look a little closer.','Glass meets metal. Every edge has a purpose.'],
      ['Nothing here<br>is incidental.','Nine groups, separated along a single axis.'],
      ['A small opening.<br><em>A different view.</em>','Nine overlapping blades shape the opening through which light passes.'],
      ['Everything,<br><em>in its place.</em>','Separate parts. One continuous idea.'],
    ],
    labels:['Front bezel','Curved glass','Retaining ring','Focus sleeve','Iris assembly','Inner optics','Stepped barrel','Rear element','Bayonet mount'],
    storyKicker:'Behind the image', storyTitle:'The part you<br><em>don’t usually see.</em>',
    storyBody:'Before there is an image, there is a path for light. Curved surfaces, a moving iris, a carefully held edge. L–01 opens that hidden arrangement to view.',
    storySmall:'A digital object study, built to be explored from the outside in.',
    details:['Nine component groups','One reversible sequence','An original 3D concept'],
    galleryKicker:'A closer inspection', galleryTitle:'Details worth<br><em>staying with.</em>',
    galleryHint:'Drag or scroll to explore', galleryPrev:'Previous detail', galleryNext:'Next detail',
    cards:[['01 / Surface','The first reflection','A curved glass surface held in a finely machined bezel.'],['02 / Mechanism','The shape of light','Nine overlapping blades. A single changing opening.'],['03 / Connection','The final connection','A stepped mount, fastening heads and brass contact pins.']],
    closing:'Made of small<br><em>decisions.</em>', closingBody:'An exploration of form, light and the space between parts.',
    footer:'L–01 is an illustrative lens concept, not an optically validated product.', concept:'Original object study · 2026',
    static:'Static view', motion:'Motion', motionOn:'Turn on reduced motion', motionOff:'Turn off reduced motion',
    fallback:'The interactive view is unavailable. Explore the lens through the stills and component notes below.',
    skip:'Skip to the study', stageAlt:'An original precision lens with blue glass, machined silver rings and nine internal groups.',
  },
  ru: {
    title:'Свет,<br><em>по слоям.</em>', kicker:'L–01 · Оптический этюд', intro:'Объектив в деталях.<br>Что стоит за каждым изображением.',
    explore:'Исследовать объектив', inside:'Внутри', notes:'Об этюде', scroll:'Листайте, чтобы открыть', back:'К объективу', replay:'Посмотреть снова',
    chapters:['Форма','Разделение','Слои','Диафрагма','Вместе'],
    captions:[['Тихое начало.','Цельный предмет. Множество точных решений.'],['Присмотритесь.','Стекло встречается с металлом. У каждой грани своя роль.'],['Здесь нет<br>случайных деталей.','Девять групп, разделённых вдоль одной оси.'],['Малое отверстие.<br><em>Другой взгляд.</em>','Девять лепестков меняют отверстие, через которое проходит свет.'],['Всё<br><em>на своём месте.</em>','Отдельные детали. Единый замысел.']],
    labels:['Передняя оправа','Выпуклое стекло','Прижимное кольцо','Кольцо фокусировки','Диафрагма','Внутренняя оптика','Корпус','Задняя линза','Байонет'],
    storyKicker:'За изображением', storyTitle:'То, чего<br><em>обычно не видно.</em>',
    storyBody:'Прежде чем появится изображение, свет проходит свой путь. Изогнутые поверхности, подвижная диафрагма, точно закреплённые края. L–01 позволяет увидеть это скрытое устройство.',
    storySmall:'Цифровой этюд о предмете — от внешней формы к внутренним деталям.',
    details:['Девять групп деталей','Обратимая анимация','Оригинальная 3D-концепция'],
    galleryKicker:'Ближе к деталям', galleryTitle:'Детали, на которых<br><em>хочется задержаться.</em>', galleryHint:'Листайте или перетаскивайте',galleryPrev:'Предыдущая деталь',galleryNext:'Следующая деталь',
    cards:[['01 / Поверхность','Первое отражение','Выпуклое стекло в тонко обработанной металлической оправе.'],['02 / Механизм','Форма света','Девять перекрывающихся лепестков. Одно меняющееся отверстие.'],['03 / Соединение','Последнее соединение','Ступенчатый байонет, крепёжные винты и латунные контакты.']],
    closing:'Состоит<br><em>из решений.</em>',closingBody:'Исследование формы, света и пространства между деталями.',footer:'L–01 — иллюстративная концепция объектива, без проверки оптических характеристик.',concept:'Оригинальный этюд · 2026',
    static:'Статичный вид',motion:'Движение',motionOn:'Уменьшить движение',motionOff:'Включить движение',fallback:'Интерактивный вид недоступен. Изучите объектив на изображениях и в описаниях ниже.',skip:'Перейти к этюду',stageAlt:'Оригинальный объектив с синим стеклом, серебристыми кольцами и девятью внутренними группами.',
  },
  kk: {
    title:'Жарық,<br><em>қабат-қабат.</em>',kicker:'L–01 · Оптикалық этюд',intro:'Бөлшектерге бөлінген объектив.<br>Кескіннің қалай пайда болатынына үңіліңіз.',
    explore:'Объективті зерттеу',inside:'Ішкі құрылым',notes:'Этюд туралы',scroll:'Ашу үшін төмен жылжытыңыз',back:'Объективке оралу',replay:'Қайта қарау',
    chapters:['Пішін','Бөліну','Қабаттар','Диафрагма','Бірлік'],
    captions:[['Байыпты бастау.','Біртұтас зат. Көптеген дәл шешім.'],['Жақынырақ қараңыз.','Шыны мен металл. Әр қырдың өз орны бар.'],['Әр бөлшектің<br>өз орны бар.','Бір ось бойымен бөлінген тоғыз топ.'],['Кішкене саңылау.<br><em>Жаңа көзқарас.</em>','Тоғыз жапырақша жарық өтетін саңылауды өзгертеді.'],['Бәрі<br><em>өз орнында.</em>','Жеке бөлшектер. Біртұтас ой.']],
    labels:['Алдыңғы жиек','Дөңес шыны','Бекіту сақинасы','Фокус сақинасы','Диафрагма','Ішкі оптика','Корпус','Артқы линза','Байонет'],
    storyKicker:'Кескіннің ар жағында',storyTitle:'Әдетте<br><em>көрінбейтін бөлік.</em>',storyBody:'Кескін пайда болғанша жарық өз жолын өтеді. Иілген беттер, қозғалатын диафрагма, дәл бекітілген жиектер. L–01 осы жасырын құрылымды көрсетеді.',storySmall:'Заттың сыртқы пішінінен ішкі бөлшектеріне дейінгі цифрлық этюд.',
    details:['Тоғыз бөлшек тобы','Қайтымды анимация','Түпнұсқа 3D-тұжырымдама'],galleryKicker:'Жақынырақ танысу',galleryTitle:'Назар аударуға<br><em>тұрарлық бөлшектер.</em>',galleryHint:'Жылжытыңыз немесе сүйреңіз',galleryPrev:'Алдыңғы бөлшек',galleryNext:'Келесі бөлшек',
    cards:[['01 / Бет','Алғашқы шағылыс','Ұқыпты өңделген металл жиектегі дөңес шыны.'],['02 / Механизм','Жарық пішіні','Тоғыз қабаттасқан жапырақша. Бір өзгермелі саңылау.'],['03 / Байланыс','Соңғы байланыс','Сатылы байонет, бекіту бұрандалары және жез түйіспелер.']],
    closing:'Әр бөлшек<br><em>өз орнында.</em>',closingBody:'Пішін, жарық және бөлшектер арасындағы кеңістік туралы этюд.',footer:'L–01 — объективтің бейнелік тұжырымдамасы. Оптикалық сипаттамалары тексерілмеген.',concept:'Түпнұсқа этюд · 2026',
    static:'Қозғалыссыз көрініс',motion:'Қозғалыс',motionOn:'Қозғалысты азайту',motionOff:'Қозғалысты қосу',fallback:'Интерактивті көрініс қолжетімсіз. Объективті төмендегі суреттер мен сипаттамалар арқылы зерттеңіз.',skip:'Этюдке өту',stageAlt:'Көк шынысы, күміс сақиналары және тоғыз ішкі тобы бар түпнұсқа объектив.',
  },
};
